### ISSUE TITLE
Black Scopes

### ISSUE THREAD

**Issue by DaddyDamocles** [Servius/tfa-sw-weapons-repository#32] opened 2018-01-11 16:19 UTC
For some reason the majority of the scopes are black. This issue is only on my StarWarsRP server but if i play a single/multiplayer hosted by me all the scopes are fine

**Comment by Servius** [comment] 2018-01-26 04:20
@DaddyDamocles Make sure you are using the TFA Redux Base or the TFA RP friendly Base. Do not use the SV Base. 

Please link the server collection if the issue is not fixed by verifiying the above.

**Closed by Servius** 2018-01-26 04:20 UTC
